server:
  port: 8080

spring:
  application:
    name: oauth2-server
  datasource:
    url: jdbc:http://localhost:6657/oauth?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver